solid/authorization-panel

- README.md
> Privacy of User's authorizations granted to Clients

- README.md
Sorry to be jumping in, but I believe that cachability is absolutely essential when it comes to acl treatment. We have to check access for every resource, and so, the acl check adds latency before first byte. Failure in this area is a potential show-stopper, so I would like to have it very high on the agenda.
> Propose cachability is a key success criteria

- Proposals/ReplaceTrustedAppsWithTags.md
this PR consolidates the proposal of #48 with the discussion in that issue and additional refining of the idea since originally proposed.
> Replace Trusted Apps with Tags

- Proposals/ChangesToWAC.md
this PR consolidates several changes and improvements to Web Access Control that i have talked about in the past. all of these ideas are implemented in [my auth server](https://github.com/zenomt/webid-auth-nginx) (and have been for some time).
> consolidated proposals for changes to WAC

- proposals/wac-ucr/index.bs
Add starting template for WAC Use Cases and Requirements
> Initialize UCR Template

- proposals/wac-ucr/index.bs
Attempt to capture the read-append-delete use case [discussed in the July 29th panel session](https://github.com/solid/authorization-panel/blob/master/meetings/2020-07-29.md).
> add read-append-write use case

- proposals/wac-ucr/index.bs
Add conditional use case that permits access based on the presence of a relationship between two resources
> add conditional-by-relationship

- proposals/wac-ucr/index.bs
Move extended network use case to inheritance section and update title per panel session [action item](https://github.com/solid/authorization-panel/blob/master/meetings/2020-09-02.md#extended-social-network---httpsgithubcomsolidauthorization-panelpull98)
> move extended network and update title

- proposals/wac-ucr/index.bs
Adds scenario where the recommender controls their own resource.
Discussed in https://github.com/solid/authorization-panel/issues/89 , agreed in https://github.com/solid/authorization-panel/blob/master/meetings/2020-08-26.md
> Add multi-storage scenario; recommender controlled

- proposals/wac-ucr/index.bs
- proposals/wac-ucr/uc-survey.md
Discussed in https://github.com/solid/specification/issues/9#issue-464920092 , agreed in https://github.com/solid/authorization-panel/blob/master/meetings/2020-08-26.md
> Use case survey

- proposals/wac-ucr/index.bs
Alice runs an open online workshop for a few people she works with but also
she sends an invitation to aa public mailing list suggesting experts
in her field should also come. ..
> Authenticated Agent  - anyone logged in

- proposals/wac-ucr/uc-survey.md
Consolidate survey responses from panelists.
> Consolidate survey

- proposals/acp/definitions.md
- proposals/acp/use-cases.md
most of these I've done with search and replace, but I did review the diff and it think changes are correct
> ACP snippet corrections

- proposals/wac-ucr/index.bs
See:
- Problem with tables https://github.com/solid/authorization-panel/commit/fc235e9469fabed347158df05328bec8ba7fbfb1#r43301927
- Problem with definition links https://github.com/solid/authorization-panel/commit/c7b2f5be3d0f13c13602c5378dc70dafb391a80c#r43342000
> Fixed dark mode styles for invisible text

- proposals/acp/enforcement-propagation.md
This is the jump of point for section 4. There are other parts to be added for the links in this page. I will add those over the weekend.
> first part of section 4 on enforcement and propagation

- proposals/acp/access-enforcement.md
Pseudo code uses TypeScript syntax. Provide the logic to determine whether an agent can access a resource using a specified HTTP method.
> pseudo code for access enforcement

- proposals/acp/access-enforcement.md
- proposals/acp/policy-propagation.md
Fixed a defect in the access enforcement. 
Added file to provide pseudo code for policy propagation for resources and containers.
> defect in access enforcement. Added policy propagation for resources

- proposals/acp/access-enforcement.md
- proposals/acp/acr-policy-propagation.md
- proposals/acp/enforcement-propagation.md
- proposals/acp/policy-propagation.md
Updated the pseudo code to use proper TypeScript. 
Added pseudo code for ACR resource manipulation. 
There are a number of classes used that are utility and therefore not provided.
The imports are also not provided. 
The purpose is not to use this as an implementation but to use it as a way 
to express the logic for ACP
> updated to TypeScript and added acr policy propagation

- meetings/2021-02-08.md
Meeting for special session to finish UCR doc on 2021-02-08
> Meeting Notes 2021-02-08 (Special Use Case and Requirements Session)

- proposals/authorization-ucr/index.bs
> fix some punctuation in index.bs

- proposals/acp/solid-acp.ttl
- proposals/acp/wac-acp-diff.ttl
Here is an initial proposal for linking together of the ACP and ACL ontologies.  
This starts addressing https://github.com/solid/authorization-panel/issues/133
> Relating ACL and ACP ontologies

- proposals/authorization-ucr/uc-survey.md
closes #192 
It seems that only *Read permissions* was added in https://github.com/solid/authorization-panel/pull/152/files#diff-970cc50352376ec44b2aefe7e5808328ae8d203737ca4fd966d2513705cc640bR130
(you will need to click 'load diff' so that line 130 shows)
@csarven do you see any other specific issues?
> tiny cleanup after #152

- proposals/wac-acp-diff-story.md
The full formatted text can be seen [here](https://github.com/solid/authorization-panel/blob/acp-diff/proposals/wac-acp-diff-story.md)
> Refine Acp diff's relation to WAC

- proposals/evaluation/uc-1-consent.md
Here I generalized the use case to something a bit more open to the web.
(For the meaning of Open see the 2 pages of the PhD thesis intro I posted here:
https://twitter.com/bblfish/status/1398230682237911041
I came across this from the talk on Monoidal Categories explained without mathematics further up in the thread.
)
> generalise use case to cover http://mesinfos.fing.org/english/

- meetings/2021-08-11.md
Apologies I missed out on some bits of the conversation @bblfish and @elf-pavlik. Might require a bit of a review this week.
> Minutes 2021-08-11

- meetings/2021-08-18.md
I was hoping to add changes that could be reviewed without needing to make a PR...
> Add TallTed's comment

- proposals/authorization-ucr/index.bs
You can see real diff by ignoring whitespaces https://github.blog/2018-05-01-ignore-white-space-in-code-review/
*EDIT* link which ignores whitespece changes https://github.com/solid/authorization-panel/pull/249/files?diff=unified&w=1
> added first delegation use case

- meetings/2021-11-17.md
Markup rendered version can be see here:
https://github.com/solid/authorization-panel/blob/draft-minutes/meetings/2021-11-17.md
> Draft minutes for 17 Nov 2021

- proposals/acp-specification/index.html
If I have understood this paragraph correctly, then I would suggest this is a simpler way of putting it.
> Simplify and fix typos

- proposals/acp-specification/acp.ttl
- proposals/acp-specification/index.html
Fixes https://github.com/solid/authorization-panel/issues/277 by removing the `acp:access` property.
> Remove ACP access

- proposals/acp-specification/acp.ttl
- proposals/acp-specification/index.html
Fixes https://github.com/solid/authorization-panel/issues/311.
> Remove acp:mode from Context properties

- proposals/acp-specification/index.html
- proposals/authorization-ucr/index.bs
> Individuals matching context with client/issuer

- README.md
we can add this correction while #322 stays open
> mark meeting as happening sporadically 
