UseCases.md
per [request](https://github.com/solid/authorization-and-access-control-panel/issues/35#issuecomment-557933524) from @elf-pavlik
=> add asymmetrical connectivity use cases

Proposals/TrustedAppsReplacement.md
In this PR we propose half of a replacement to trusted apps.
Other half coming later.
=> TrustedAppsReplacement

proposals/wac-ucr/index.bs
Given people's experience with Twitter this type of use case seems very realistic. One wants to be able to edit a post but only until it itself has been commented on.
This use case can then also be referred to by other use cases such as the read-append-delete use case.
https://github.com/solid/authorization-panel/pull/94
=> Access until action

proposals/wac-ucr/index.bs
Allowing people to fight spam on their blog posts without creating a filtering bottleneck.
Following on the Minimal Credentials Disclosure use case 
https://github.com/solid/authorization-panel/pull/95#pullrequestreview-461749127
=> Public commenting for extended social network

proposals/wac-ucr/index.bs
The ability to allow Minimal Credential Disclosure is an important aspect Authorization schemes.
A quick search gave me this paper: 
https://link.springer.com/article/10.1007/s12394-009-0022-6
=> Add Minimal Credential Disclosure ex. in Privacy

proposals/wac-ucr/index.bs
This high confidentiality scenario partly explains some aspects of LDP Containers.
=> A high confidentiality scenario that one should not forget

proposals/wac-ucr/index.bs
This makes a slight adjustment to the multi-store use case to append to a single resource instead of a container, since this is in the basic resource access section (permissions for a single resource).
=> update multi-storage to append link to resume

proposals/wac-ucr/index.bs, proposals/wac-ucr/uc-survey.md
Update the survey to include recently adding use cases (#95, #97, #98, #99, #100)
Also caught that a use case had been accidentally removed in one of the other merges, so I added that back in.
=> add new use cases to survey, re-add missing

proposals/wac-ucr/index.bs
Some mentions about the notion to block bad actors:
* https://github.com/solid/authorization-panel/issues/111
* https://github.com/solid/authorization-panel/issues/115
* https://csarven.ca/linked-research-decentralised-web#addressing-social-implications
* https://dr.amy.gy/chapter3
* https://github.com/solid/authorization-panel/blob/master/proposals/TrustedAppsReplacement.md
* https://www.w3.org/2001/tag/doc/ethical-web-principles/#community (re initial Solid proposal to adopt Ethical Web Principles: https://lists.w3.org/Archives/Public/public-solid/2019Jun/0000.html )
This is a widely known issue to acknowledge. Plethora of examples and studies out there. Important in many areas: journalism, social web, scholarly communication..
=> Add use case to block access to bad actors

proposals/wac-ucr/index.bs
This will give us clear reference for restricting application access while not acting as resource controller.
@justinwb you may need to fix headings since other use case for constraining applications wasn't under a lower level heading.
=> use case: client constraints

proposals/wac-ucr/index.bs
Based off a number of existing discussions and work:
* https://github.com/solid/authorization-panel/issues/58
* https://github.com/linkeddata/dokieli/issues/96
* https://github.com/linkeddata/dokieli/issues/137
* https://github.com/solid/specification/issues/171
Certainly there are other issues lying around... and this is a fairly common. It also goes along with some of the other use cases.
Aside: https://github.com/solid/specification/pull/210
=> Add use case for client to discover access privileges

meetings/2021-01-13.md, proposals/wac-ucr/uc-survey.md
It is often difficult while taking notes during a meeting to clearly
spell out what was said. Even if one should try to capture as much as
possible during the meeting, it helps for those present to go over the
notes, improve the spelling, add links dropped in the chat, and clean
it up so that people who could not make it can later follow the
dialogue more clearly, and for all at a later date to be able to
remember what was said.
So I propose that instead of directly pushing the notes to the github
repo, we instead push it as a PR like here, and ask everyone to go
over it, adding fixes if needed. Then at the beginning of each session
we can ask everyone if they are satisfied with the recording, and push
the PR.
This was how it was done in the LDP WG, but without the benefit of
Github.
=> Meeting notes for 2021-01-13

proposals/wac-ucr/index.bs
This use case presents scenario of group based access which doesn't require public group member list. Neither party granting access maintaining their own list of members in group they grant access to.
**EDIT**: https://solid.github.io/authorization-panel/wac-ucr/#capabilities-vc provides more complicated use case which depends on existence of broader trust network. Use case in this PR only requires membership credential issued by a known party. It also directly addresses known issues with group based access where list of group members is not accessible to the guard enforcing access policy.
=> Use case: group membership vc

proposals/wac-ucr/index.bs, proposals/wac-ucr/uc-survey.md
This PR adds discrete access modes to create and delete resources, vs. the legacy wac behavior that bundles them into write and append.
**Note:** this PR is a branch off of https://github.com/solid/authorization-panel/pull/152
=> Add create and delete modes

proposals/authorization-ucr/index.bs
Solution-centric references have no place in a UCR document.
Had there been a prior UCR document, then this current UCR would be an addendum to the prior UCR as additional needs are brought forward, and not because of particular solutions.
=> Omit solution-centric references

proposals/authorization-ucr/index.bs
Access relationships may span multiple hops, may include incoming arcs, and may appear in any document.
This PR clarifies the axis vocabulary we'll need to standardize the scope of such access relationships.
=> + characterize axes for access relationships

ldn-access-request.md
Status: draft intended for feedback.
This PR follows up on https://github.com/solid/app-authorization-panel/issues/27 by providing a generic mechanism that allows agents to request permissions to resources. It supports:
- one or multiple agents
- groups
- for all apps or for specific apps
- different modes (Read / Append / Write / Control)
- for one or multiple resources
- multiple permissions blocks for different agents
- any future extensions to WebACL documents
As currently drafted, it also supports:
- requesting append operations to any RDF document
=> Propose access request with LDN

.github/ISSUE_TEMPLATE/config.yml, .github/ISSUE_TEMPLATE/draft-suggestion.md, .github/ISSUE_TEMPLATE/use-case-suggestion.md
As discussed during our call today. This will show links to github discussion and gitter chatroom. As well as two option to create issues:
* Proposal suggestion
* Use case suggestion
We can add more option with appropriate templates as needed. We can also add PR templates, for example one for survey responses.
=> add issue templates

meetings/2021-04-28.md
These probably could use a bit of improvement.
=> Minutes 2021-04-28

proposals/acp/definitions.md, proposals/acp/use-cases.md, proposals/acp/wac-acp-diff.ttl, proposals/wac-acp-diff-story.md
Fixes https://github.com/solid/authorization-panel/issues/145.
I think we can remove the straight references to `acp:AccessPolicy` in sample code for now to avoid confusion. In the longer term, once the first draft of a draft of ACP gets merged into main, we could move the first acp proposal to the archive folder or delete it from the `main` branch.
cc @bblfish
=> Remove references to acp:AccessPolicy

proposals/wac-acp-diff-story.md
acl:AccessControl in acp examples
=> Typos in example

proposals/evaluation/uc-0-effective-acr.md, proposals/evaluation/use-cases.md
A simple description of how effective access control resources are discovered.
That mechanism will hold for all Use Case, so in order to avoid unnecessary repetition, it is here factored out.
=> Effective ACR discovery

meetings/2021-09-29.md
The content was pushed straight to the repo. But I thought I'd PR improvements here.
=> Meeting 2021-09-29 patches

proposals/evaluation/uc-2.5.2-client-constraints.md
During the last meeting we discussed how matcher using `acp:agent` can be combined with matcher using `acp:client` to express policy for a specific user using the specific client.
=> added evaluation for 2.5.2 client-constraints

proposals/acp-specification/index.html
There are now 4 named individuals so perhaps leave the text open to the number changing again.
=> Fix incorrect number of named individuals

proposals/acp-specification/acp.ttl
Add missing prefix directive for `cito` prefix, in ACP ontology file.
=> ACP: Add missing prefix id directive for `cito`

proposals/authorization-ucr/index.bs
Obsolete bibref [breaks](https://github.com/solid/authorization-panel/actions/runs/3140870105/jobs/5102710907) bikeshead build.
=> UCR: Update obsolete bibref

proposals/acp-specification/index.html
Addresses acceptance criterion 1 of #319.
---
In case we decide to stay with `http` for the vocabulary base URI, this change modifies pseudocode to fit.
In my opinion we should not merge this but use `https` instead everywhere in the spec.
=> HTTP vocabulary base URI in pseudocode

README.md
Action following multiple cases of uncertainty (cf. [matrix](https://matrix.to/#/!rUzJAFxzsTfTWEIQfp:gitter.im/$xEtmuBLbL7tVWIDI8gKVM1wh3u-LLlJIzLsJPOB674g?via=gitter.im&via=matrix.org&via=t2bot.io)), and looking ahead to the special topic meeting on this 2023-10-10. Can be reverted if decision turns out to keep panel meetings alive.
=> Fix: refer to general and special CG meetings

proposals/acp-specification/index.html
PR updates the SotD section given that the [Solid CG Charter](https://www.w3.org/community/solid/charter/) supersedes Solid Process.
=> Remove mention of Solid Process from SotD
